name: vmango
channels:
  - fredboudon
  - conda-forge
  - anaconda
dependencies:
  - openalea.lpy
  - openalea.mtg
  - r
  - toml
  - future
  - rpy2
  - pandas
  - numpy
  - mesa-libgl-cos6-x86_64
  - mesa-libgl-devel-cos6-x86_64
  - pip
  - pip:
     - git+https://github.com/fredboudon/vmango.git
