name: vmango
channels:
  - fredboudon
  - conda-forge
dependencies:
  - openalea.lpy
  - openalea.mtg
  - r
  - toml
  - future
  - rpy2
  - pandas
  - numpy
  - pip:
     - git+https://github.com/fredboudon/vmango.git
